"""
Auth service for Ma'at Legal AI.

Provides authentication, authorization, and user management.
"""

from server.auth.dependencies import (
    auth_rate_limit_dependency,
    get_current_active_user,
    get_current_session,
    get_current_user,
    get_current_user_id,
    get_optional_user,
    require_session,
    require_verified_user,
)
from server.auth.models import (
    ApiKeyCreateRequest,
    ApiKeyResponse,
    AuthResponse,
    AvailableModelsResponse,
    ChangePasswordRequest,
    EmailVerificationRequest,
    ForgotPasswordRequest,
    LoginRequest,
    MessageResponse,
    PasswordResetConfirmRequest,
    PasswordResetRequest,
    RefreshTokenRequest,
    RegisterRequest,
    ResetPasswordRequest,
    SessionInfoResponse,
    SessionRevokeRequest,
    SessionsListResponse,
    TokenResponse,
    UserResponse,
)
from server.auth.rate_limiter import (
    RateLimitConfig,
    RateLimitResult,
    RateLimitScope,
    check_rate_limit,
    get_rate_limit_config,
    get_rate_limit_status,
    reset_rate_limit,
)
from server.auth.redis_client import (
    close_redis,
    get_redis,
    get_redis_dependency,
    init_redis,
    redis_lifespan,
)
from server.auth.router import router
from server.auth.security import (
    create_access_token,
    create_password_reset_token,
    create_refresh_token,
    create_token_pair,
    decode_token,
    get_token_expiration,
    get_token_jti,
    get_token_type,
    get_token_user_id,
    hash_password,
    is_token_blacklisted,
    is_token_expired,
    refresh_access_token,
    refresh_token_pair,
    revoke_token,
    validate_password_strength,
    verify_password,
)
from server.auth.security_events import (
    SecurityEvent,
    SecurityEventSeverity,
    SecurityEventType,
    get_security_event_count,
    get_security_events,
    log_security_event,
    log_security_event_kwargs,
)
from server.auth.session_manager import (
    SessionInfo,
    create_session,
    get_session,
    get_session_count,
    list_user_sessions,
    revoke_all_sessions,
    revoke_session,
    update_session_activity,
)
from server.auth.token_blacklist import (
    blacklist_access_token,
    blacklist_refresh_token,
    blacklist_user_tokens,
    get_blacklist_stats,
    is_access_token_blacklisted,
    is_refresh_token_blacklisted,
)

__all__ = [
    # Router
    "router",
    # Redis
    "init_redis",
    "close_redis",
    "get_redis",
    "get_redis_dependency",
    "redis_lifespan",
    # Token Blacklist
    "blacklist_access_token",
    "blacklist_refresh_token",
    "is_access_token_blacklisted",
    "is_refresh_token_blacklisted",
    "blacklist_user_tokens",
    "get_blacklist_stats",
    # Rate Limiter
    "RateLimitConfig",
    "RateLimitResult",
    "RateLimitScope",
    "check_rate_limit",
    "get_rate_limit_config",
    "get_rate_limit_status",
    "reset_rate_limit",
    # Session Manager
    "SessionInfo",
    "create_session",
    "get_session",
    "list_user_sessions",
    "revoke_session",
    "revoke_all_sessions",
    "get_session_count",
    "update_session_activity",
    # Security Events
    "SecurityEvent",
    "SecurityEventType",
    "SecurityEventSeverity",
    "log_security_event",
    "log_security_event_kwargs",
    "get_security_events",
    "get_security_event_count",
    # Security
    "create_access_token",
    "create_refresh_token",
    "create_password_reset_token",
    "create_token_pair",
    "decode_token",
    "get_token_user_id",
    "get_token_type",
    "get_token_jti",
    "get_token_expiration",
    "is_token_expired",
    "is_token_blacklisted",
    "revoke_token",
    "validate_password_strength",
    "verify_password",
    "hash_password",
    "refresh_access_token",
    "refresh_token_pair",
    # Dependencies
    "get_current_user_id",
    "get_current_user",
    "get_current_active_user",
    "get_current_session",
    "get_optional_user",
    "require_session",
    "require_verified_user",
    "auth_rate_limit_dependency",
    # Models
    "AuthResponse",
    "AvailableModelsResponse",
    "LoginRequest",
    "RefreshTokenRequest",
    "RegisterRequest",
    "TokenResponse",
    "UserResponse",
    "PasswordResetRequest",
    "PasswordResetConfirmRequest",
    "EmailVerificationRequest",
    "SessionRevokeRequest",
    "ApiKeyCreateRequest",
    "ApiKeyResponse",
    "SessionInfoResponse",
    "SessionsListResponse",
    "MessageResponse",
    "ChangePasswordRequest",
    "ForgotPasswordRequest",
    "ResetPasswordRequest",
]
